image: codefresh/plugin-helm
tag: master
version: 1.0.0
description: Release a Helm chart (update or install)
keywords:
  - helm
  - kubernetes
home: https://github.com/codefresh-io/cf-plugin-helm
sources:
  - https://github.com/codefresh-io/cf-plugin-helm
maintainers: # (optional)
  - name: Alexei Ledenev
    email: alexei@codefresh.io
icon: https://avatars0.githubusercontent.com/u/29493517?v=4&s=400
envs:
  - name: CHART_NAME
    type: required
    description: Helm chart name to release
  - name: RELEASE_NAME
    type: required
    description: Helm release name
  - name: NAMESPACE
    description: target Kubernetes namespace
  - name: CHART_VERSION
    description: application chart version to install
  - name: CHART_REPO_URL
    description: Helm chart repository URL
  - name: DRY_RUN
    description: do a "dry run" installation (do not install anything, useful for Debug)
  - name: DEBUG
    description: print verbose install output
  - name: WAIT
    description: block step execution till installation completed and all Kubernetes resources are ready
  - name: TIMEOUT
    description: wait timeout (5min by default)
volumes:
  - name: /root/.kube/config
    required: true
    description: Kubernetes configuration file (**TODO** need to be implemented)